#!/bin/bash

# Deployment script to fix database issues on Ubuntu server

echo "🚀 Deploying database fix to Ubuntu server..."

# Instructions for manual deployment
echo ""
echo "📋 Manual Deployment Instructions:"
echo ""
echo "1. Copy the fix_database.py file to your Ubuntu server:"
echo "   scp fix_database.py ubuntu@your-server-ip:~/ic-bot/"
echo ""
echo "2. SSH into your Ubuntu server:"
echo "   ssh ubuntu@your-server-ip"
echo ""
echo "3. Navigate to the ic-bot directory:"
echo "   cd ~/ic-bot"
echo ""
echo "4. Activate the virtual environment:"
echo "   source venv/bin/activate"
echo ""
echo "5. Run the database fix script:"
echo "   python3 fix_database.py"
echo ""
echo "6. Restart the bot:"
echo "   pkill -f 'python3 main.py'"
echo "   nohup python3 main.py > bot.log 2>&1 &"
echo ""
echo "7. Check the logs:"
echo "   tail -f bot.log"
echo ""
echo "✅ The database should now be properly initialized!"
echo ""
echo "🔧 If you still see errors, check:"
echo "   - Database file permissions"
echo "   - Virtual environment activation"
echo "   - Python dependencies"
echo "   - tiles.json file exists in data/ directory" 